// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    IAkarIconsCircleMinusFill: typeof import('~icons/akar-icons/circle-minus-fill')['default']
    IAkarIconsCirclePlusFill: typeof import('~icons/akar-icons/circle-plus-fill')['default']
    IAkarIconsPlay: typeof import('~icons/akar-icons/play')['default']
    IArcticonsTenbitclockwidget: typeof import('~icons/arcticons/tenbitclockwidget')['default']
    ICarbon4k: typeof import('~icons/carbon/4k')['default']
    ICarbonAccessibility: typeof import('~icons/carbon/accessibility')['default']
    ICarbonChevronDown: typeof import('~icons/carbon/chevron-down')['default']
    ICarbonChevronLeft: typeof import('~icons/carbon/chevron-left')['default']
    ICarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    ICarbonChevronUp: typeof import('~icons/carbon/chevron-up')['default']
    ICarbonEmail: typeof import('~icons/carbon/email')['default']
    ICarbonForecastLightning: typeof import('~icons/carbon/forecast-lightning')['default']
    ICarbonPassword: typeof import('~icons/carbon/password')['default']
    ICarbonPauseOutlineFilled: typeof import('~icons/carbon/pause-outline-filled')['default']
    ICarbonView: typeof import('~icons/carbon/view')['default']
    ICarbonViewOff: typeof import('~icons/carbon/view-off')['default']
    IIconParkTwotoneReplayMusic: typeof import('~icons/icon-park-twotone/replay-music')['default']
    IIconParkTwotoneRest: typeof import('~icons/icon-park-twotone/rest')['default']
    IIconParkTwotoneResting: typeof import('~icons/icon-park-twotone/resting')['default']
    IMdiAccount: typeof import('~icons/mdi/account')['default']
    IMdiAccountBox: typeof import('~icons/mdi/account-box')['default']
    IPixelarticonsFlag: typeof import('~icons/pixelarticons/flag')['default']
    IPixelarticonsForward: typeof import('~icons/pixelarticons/forward')['default']
    IPixelarticonsHourglass: typeof import('~icons/pixelarticons/hourglass')['default']
    IPixelarticonsPause: typeof import('~icons/pixelarticons/pause')['default']
    IPixelarticonsPlay: typeof import('~icons/pixelarticons/play')['default']
    IPixelarticonsRepeat: typeof import('~icons/pixelarticons/repeat')['default']
    IPixelarticonsWatch: typeof import('~icons/pixelarticons/watch')['default']
    ISystemUiconsBookmark: typeof import('~icons/system-uicons/bookmark')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
