// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ICarbonCaretLeft: typeof import('~icons/carbon/caret-left')['default']
    ICarbonCheckmarkFilled: typeof import('~icons/carbon/checkmark-filled')['default']
    ICarbonEmail: typeof import('~icons/carbon/email')['default']
    ICarbonErrorOutline: typeof import('~icons/carbon/error-outline')['default']
    ICarbonPassword: typeof import('~icons/carbon/password')['default']
    ICarbonView: typeof import('~icons/carbon/view')['default']
    ICarbonViewOff: typeof import('~icons/carbon/view-off')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
